# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7dec737bbcbbc4418a5058d5a72004912ec181d298f8149a545c5d34378dee1d2ee0189d009f0afe257a9813df9978bf6f418603a41830918dcc858225bad6f0
  twilio_account_sid: AC87bf79ddc02272dac2140e3045662f7a
  twilio_auth_token: a94fd25920be0dfc89cfbe36b4101ebc
  twilio_phone_number: +15005550006

test:
  secret_key_base: 120b573ffbf4f0a29b66f859fd2d81454c3ba0a62006c5ef54b42785fd9371c284f0dbae1f8328365a4503773d69abb4ed88580669e298ebfbd7d2f85ac84a4e
  twilio_account_sid: AC87bf79ddc02272dac2140e3045662f7a
  twilio_auth_token: a94fd25920be0dfc89cfbe36b4101ebc
  twilio_phone_number: +15005550006

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  email_provider_username: <%= ENV["EMAIL_PROVIDER_USERNAME"] %>
  email_provider_apikey: <%= ENV["EMAIL_PROVIDER_APIKEY"] %>
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>
  twilio_phone_number: <%= ENV["TWILIO_PHONE_NUMBER"] %>

